# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('encrypted_password', models.CharField(max_length=256)),
                ('salt', models.CharField(max_length=256)),
                ('encrypt_cycle', models.IntegerField(default=25000)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
